### ISSUE TITLE
VSCode plugin does not do the same as online editor

### ISSUE THREAD

**Issue by Danny-Engelman** [hikerpig/pintora#15]
The code from the website: https://pintorajs.vercel.app/docs/diagrams/er-diagram/

does not work in the VSCode plugin

![](https://i.imgur.com/uShf8hE.png)

**Comment by hikerpig** [comment]
@Danny-Engelman Thank you for the feedback. I suppose there is an extra space after line 4 'PK', like the screenshot below. Actually the online editor will also fail on this.
 
![image](https://user-images.githubusercontent.com/2259688/153711399-0b1d16ec-baad-42ac-b784-c781616a09a2.png)

Current grammar is too sensitive about whitespaces, I will fix the erDiagram and publish a new version later.
Also I'm working on some better solutions #13 , hope this kind of problem won't appear in the future.

**Comment by hikerpig** [comment]
This bug is fixed in @pintora/standalone@0.1.1 and  the vscode extension 0.4.8  🎉

**Comment by Danny-Engelman** [comment]
Thanks for being so quick.

I had copy pasted the example from your website to VSCode

**Comment by hikerpig** [comment]
> Thanks for being so quick.
> 
> I had copy pasted the example from your website to VSCode

I tried the copy and paste but it seemed OK, until I start typing randomly and it became like the screenshot. Also the parser error message matched.

Could you upgrade the vscode extension  and see if it is OK now？ If it still fails, I may try to dig deeper. 🙊

**Comment by Danny-Engelman** [comment]
Sorry, you are not there yet.

I updated the plugin and did not update the Pintora, error

I then tried all examples from the site, similar errors


![](https://i.imgur.com/tATaICY.png)

**Comment by hikerpig** [comment]
@Danny-Engelman  I see there is a `\r` in your error message, could be the new line character. Are you using Windows or is your VSCode use CRLF for newlines ?

This was kind of a blind spot for me, but now I may know how to reproduce it.

**Comment by Danny-Engelman** [comment]
Yes, I am on W11
But this LF issue is known on all versions.

**Succes!**

I refreshed the plugin, did NOT change the failing code, and the diagram is now correctly previewed.
