### ISSUE TITLE
[BUG] Incorrect display of forks in groups in activity diagrams

### ISSUE THREAD

**Issue by gltjk** [hikerpig/pintora#169]
In the activity diagram, when a fork is inside a group, the fork node and the join node are not long enough.

Here is the tested code:
```
activityDiagram
title: Fork inside group test
start
group Group {
  fork
    :a;
  forkagain
    :b;
  endfork
}
end
```

Here is an [online example](https://pintorajs.vercel.app/demo/live-editor/?code=YWN0aXZpdHlEaWFncmFtJTBBdGl0bGUlM0ElMjBGb3JrJTIwaW5zaWRlJTIwZ3JvdXAlMjB0ZXN0JTBBc3RhcnQlMEFncm91cCUyMEdyb3VwJTIwJTdCJTBBJTIwJTIwZm9yayUwQSUyMCUyMCUyMCUyMCUzQWElM0IlMEElMjAlMjBmb3JrYWdhaW4lMEElMjAlMjAlMjAlMjAlM0FiJTNCJTBBJTIwJTIwZW5kZm9yayUwQSU3RCUwQWVuZA%3D%3D&config=JTdCJTIydGhlbWVDb25maWclMjIlM0ElN0IlMjJ0aGVtZSUyMiUzQSUyMmRlZmF1bHQlMjIlN0QlMkMlMjJzZXF1ZW5jZSUyMiUzQSU3QiU3RCUyQyUyMmVyJTIyJTNBJTdCJTdEJTJDJTIyY29tcG9uZW50JTIyJTNBJTdCJTdEJTJDJTIyYWN0aXZpdHklMjIlM0ElN0IlN0QlMkMlMjJtaW5kbWFwJTIyJTNBJTdCJTdEJTdE) of the code above.

![image](https://github.com/hikerpig/pintora/assets/1887124/331936d0-3f63-4c09-8f86-59c61d551d71)

**Comment by hikerpig** [comment]
This is fixed in v0.6.3
