### ISSUE TITLE
Using Pintora as a library in Node.js

### ISSUE THREAD

**Issue by tex0l** [hikerpig/pintora#174]
Hi,
I moved from Mermaid to Pintora for my blog in Astro because I need SSR (see https://github.com/mermaid-js/mermaid/issues/3650), and solutions involving pupeteer end up with a result which is not consistent across browsers, contrary to what I've seen with Pintora.

However, the documentation to use Pintora as a library is really confusing (or non-existent), it's designed to be used in Node.js as a CLI only, not a as a library.

I circumvented the issue to generate an SVG from a string in a Node.js script by importing the `render` function from `'@pintora/cli'`:
```typescript
import {render} from '@pintora/cli'
import type {PintoraConfig} from '@pintora/standalone'

const buildSVG = async (code: string, config: PintoraConfig) => {
  const result = await render({
    code: code,
    pintoraConfig: config,
    mimeType: 'image/svg+xml'
  })
}
```

In the [API usage](https://pintorajs.vercel.app/docs/advanced/api-usage/) documentation, there is no mention of how to use the CLI's Node.js APIs, and no mention of how to use the `'@pintora/standalone'` package to generate an SVG from a string.

I would suggest to either:
- document the API of `'@pintora/cli'`
- or to embed within `'@pintora/standalone'` the render function from `'@pintora/cli'` which allows using it in a Node.js script.

**Comment by hikerpig** [comment]
Thank you for the try and this feedback, I'll look into it this weekend.

**Comment by hikerpig** [comment]
I've added a little basic demostration for this usage. https://pintorajs.vercel.app/docs/advanced/api-usage/#pintora-api-in-nodejs-pintoracli
