### ISSUE TITLE
 Feature Request: support WinterCG environment

### ISSUE THREAD

**Issue by hikerpig** [hikerpig/pintora#227]
Seperating from issue #225 .

It'd be cool if pintora can run in [WinterCG](https://wintercg.org/)  environment. 

Maybe I can start with trying to run pintora in https://github.com/wasmerio/winterjs

**Comment by hikerpig** [comment]
winterjs is relatively new and unstable for now, so I chose to test pintora in Vercel's edge-runtime.
I managed to to replace all Node.js module with JS polyfill and bundle the whole pintora and its runtime dependency into one   JS file. As demonstrated in a conceptual demostration in #233 .
Currently:
1. text-metric will need to be implemented correctly, maybe I can try something like `fontkit`
2. only `svg` renderer is supported in this runtime

**Comment by atian25** [comment]
Regarding the second point you mentioned, Pintora does not need to support other formats; developers can simply use @resvg/resvg-wasm to convert to PNG as needed.

**Comment by hikerpig** [comment]
@atian25 I'm not sure how are you going to use it but we can have a try and improve it later, see the docs in https://pintorajs.vercel.app/docs/advanced/api-usage/#pitora-in-wintercg-runtime

**Comment by atian25** [comment]
cool~ I'll try it later today.

**Comment by atian25** [comment]
https://bots-test.fn.goofy-edge.cn/api/uml?api/uml?code=%0A%20%20mindmap%0A%20%20title%3A%20Mind%20Map%20levels~~%0A%20%20*%20UML%20Diagrams%0A%20%20**%20Behavior%20Diagrams%0A%20%20***%20Sequence%20Diagram%0A%20%20***%20State%20Diagram%0A

it works~

**Comment by hikerpig** [comment]
I see the output image of your demo is kind of blury, but it's a good start. Now that it can run in edge-runtime and goofy worker.

I've also gave a try on [wasmerio/winterjs](https://github.com/wasmerio/winterjs), it works without error in Pintora's side, but has some trouble with fetch event handler https://github.com/wasmerio/winterjs/issues/37, let's give it some time.

**Comment by atian25** [comment]
https://bots-test.fn.goofy-edge.cn/api/uml2svg?code=%0A%20%20mindmap%0A%20%20title%3A%20Mind%20Map%20levels~~%0A%20%20*%20UML%20Diagrams%0A%20%20**%20Behavior%20Diagrams%0A%20%20***%20Sequence%20Diagram%0A%20%20***%20State%20Diagram%0A

This is for generating an svg using only pintora.
The previous URL may be a problem with the use of resvg.

**Comment by hikerpig** [comment]
Text metric will absolute be a problem when you use CJK characters.
I'll see what I can do with font loading next week.
