### ISSUE TITLE
Unnecessary stroke around note text results in hard to read content

### ISSUE THREAD

**Issue by titanism** [hikerpig/pintora#241]
<img width="685" alt="Screen Shot 2024-01-04 at 7 15 47 PM" src="https://github.com/hikerpig/pintora/assets/101466223/2708f416-30d2-465d-ac07-d3dc02137707">
<img width="1040" alt="Screen Shot 2024-01-04 at 7 15 52 PM" src="https://github.com/hikerpig/pintora/assets/101466223/988a77db-f299-44db-ac86-d7ce473fd67e">

**Comment by hikerpig** [comment]
The stroke around note text needs to be removed. I will fix it this week.

**Comment by hikerpig** [comment]
I've merged the fix but this needs to wait for next version
