### ISSUE TITLE
[activityDiagram] Should draw a no-action-line when there is no else block

### ISSUE THREAD

**Issue by hikerpig** [hikerpig/pintora#249]
![image](https://github.com/hikerpig/pintora/assets/2259688/a468c57e-9809-4cd0-ae70-896b100fbeda)

**Comment by hikerpig** [comment]
This is fixed in v0.7.0

**Comment by taylorh140** [comment]
Just verified thanks so much:
![image](https://github.com/hikerpig/pintora/assets/10996543/a7c2856b-3a45-4084-ab37-8400affa57e7)
