### ISSUE TITLE
Special characters in activityDiagram

### ISSUE THREAD

**Issue by enzonotario** [hikerpig/pintora#287]
Hi there! Is there any way to use special characters in Simple Actions? ([like in Mermaid](https://mermaid.live/edit#pako:eNo1kE1PwzAMhv9K5BNoXZX0K03GkEDjyAlOLBysJt0qtckUUmBU_e9kneaLrfe1H9meoHHagIS2dz_NEX0g7ztlSYynvYLWeXL3jZ50ZEvoJqaHLbExr1b3Cj7Jev1IniGBwfgBOx0502VYQTiawSiQsdSmxbEPCpSdYyuOwb2dbQMy-NEkMJ40BrPr8OBxuIkntCAn-AXJsjxlVSlowXjFMyZYAueLzFJa5KLkecGLgmf1nMCfc5FA06qkZc1pzQQVjAu-8D4W84o3ugvOv14vXx5w2-NlcUC22H-Z-R_mxVSR))

I tried it in Pintora, but can't find a way: https://pintorajs.vercel.app/demo/live-editor/?code=YWN0aXZpdHlEaWFncmFtJTBBc3RhcnQlMEElMjAlMjAlMjAlMjAlM0Fmb3IlMjAlMjh2YXIlMjBpJTIwJTNEJTIwMCUzQiUyMGklMjAlM0MlM0QlMjBuJTNCJTIwaSsrJTI5JTNCJTBBZW5k&config=JTdCJTIydGhlbWVDb25maWclMjIlM0ElN0IlMjJ0aGVtZSUyMiUzQSUyMmxpZ2h0JTIyJTdEJTJDJTIyc2VxdWVuY2UlMjIlM0ElN0IlN0QlMkMlMjJlciUyMiUzQSU3QiU3RCUyQyUyMmNvbXBvbmVudCUyMiUzQSU3QiU3RCUyQyUyMmFjdGl2aXR5JTIyJTNBJTdCJTdEJTJDJTIybWluZG1hcCUyMiUzQSU3QiU3RCU3RA%3D%3D

Thanks!

**Comment by hikerpig** [comment]
Thank you for the suggestion, I will try to add a feature for quoted words in activityDiagram. ❤️

**Comment by hikerpig** [comment]
A PR adds the ability to use quoted words as action message

```
activityDiagram
start
    :"for (var i = 0; i <= n; i++)";
end
```

**Comment by enzonotario** [comment]
Nice @hikerpig , I was trying it to convert "code to flowchart", but since this issue I was trying to do it with Mermaid. I will try Pintora again now that it's fixed. Thanks so much!
