### ISSUE TITLE
Allow switching off the border of a participantBox in Sequence Diagram

### ISSUE THREAD

**Issue by RolfBremer** [hikerpig/pintora#291]
It would be nice to have participant boxes defined only by their background, without surrounding lines. 
The diagram is much more clear then. 
I found settings for the padding an background color, but none for the border.

I really like the package, btw.!

**Comment by hikerpig** [comment]
Sure, this new param `paritipantBorderColor` will do .
Wait for the PR to be merged and new package version published.
[An example](https://pintorajs-dfzx2osnx-hikerpigs-projects.vercel.app/demo/live-editor/?code=c2VxdWVuY2VEaWFncmFtJTBBJTIwJTIwQHBhcmFtJTIwcGFydGljaXBhbnRCb3JkZXJDb2xvciUyMHRyYW5zcGFyZW50JTBBJTIwJTIwYm94JTIwJTIzZTdmMmZmJTIwJTIyRW5nbGlzaCUyMENvcm5lciUyMiUwQSUyMCUyMHBhcnRpY2lwYW50JTIwQSUwQSUyMCUyMHBhcnRpY2lwYW50JTIwQiUwQSUyMCUyMGVuZGJveCUwQSUwQSUyMCUyMEElMjAtJTNFJTNFJTIwQiUzQSUyMEhlbGxvJTBBJTIwJTIwQiUyMC0lM0UlM0UlMjBDJTNBJTIwSG9sYQ%3D%3D&config=JTdCJTIydGhlbWVDb25maWclMjIlM0ElN0IlMjJ0aGVtZSUyMiUzQSUyMmRlZmF1bHQlMjIlN0QlMkMlMjJzZXF1ZW5jZSUyMiUzQSU3QiU3RCUyQyUyMmVyJTIyJTNBJTdCJTdEJTJDJTIyY29tcG9uZW50JTIyJTNBJTdCJTdEJTJDJTIyYWN0aXZpdHklMjIlM0ElN0IlN0QlMkMlMjJtaW5kbWFwJTIyJTNBJTdCJTdEJTdE)

<img width="1074" alt="image" src="https://github.com/hikerpig/pintora/assets/2259688/29780a36-0068-426d-8b57-d2a5cb330b5e">

**Comment by RolfBremer** [comment]
We updated the `pintora/cli` package to 0.7.5, but the `paritipantBorderColor` setting does not work at all.
We tried it in the vscode preview as well as with the pintora command line. We tried `tranparent` as well as `red`, but no success.

**Comment by RolfBremer** [comment]
Yes, it is also 0.7.4.

**Comment by RolfBremer** [comment]
Got the VSCode Extension today, but it says `deepmerge$1 is not a function` in the preview window.

**Comment by hikerpig** [comment]
@RolfBremer Yeah I made some mistakes publishing the vscode extension last night. Sorry about that.
Try pintora-vscode 0.9.5 and it's alright now.
<img width="1110" alt="image" src="https://github.com/hikerpig/pintora/assets/2259688/4084be98-c1fd-4f21-837b-5eaad5ce8002">

**Comment by RolfBremer** [comment]
VSCode extension 0.9.5 works like a charm now! Thank you!
The npm package 0.9.4 still does not.

**Comment by RolfBremer** [comment]
We tried the npm package with node versions 18.16, 20.10, 20.11.1 and 20.14, but no success. 
The box border is always black.

**Comment by hikerpig** [comment]
Mind I ask how do you use it ? Do you
1. use `pintora` cli directly ?
2. import `@pintora/cli` as a package and write some other code to call its exported methods?

**Comment by RolfBremer** [comment]
We used it like option 1.:
```
pintora render -i test.pintora -o test.svg
```

**Comment by hikerpig** [comment]
I think I found the reason, I don't have a clean output directory in my laptop, some old files stays in it.

@RolfBremer try `@pintora/cli@0.7.6` , I've tested it with option 1, it works.

Thank you for the try.

**Comment by RolfBremer** [comment]
Now it works! Great!
Thank you!

**Comment by RolfBremer** [comment]
I am not sure who is supposed to close an issue. For me, this is solved, so I dare to close it.
