### ISSUE TITLE
是否考虑用electron制作一个独立的编辑器软件？

### ISSUE THREAD

**Issue by TaiYouWeb** [hikerpig/pintora#307]
你好，是否有计划制作一个独立的编辑器，类似typora一样，可以直接使用，而不是作为VSCode插件来使用？
如果没有这个计划，那么是否可以给我点 实现 pintora 所见即所得 独立编辑器的 制作思路？
主要功能就是 markdown 以及 pintora 的所见即所得 编辑器。

~~~markdown
```pintora
...write some pintora dsl
```
~~~

**Comment by hikerpig** [comment]
https://pintorajs.vercel.app/demo/live-editor 可以作为一个 PWA 应用离线使用的，Edge 和 Chrome 应该都有作为 app 添加的方式。

**Comment by TaiYouWeb** [comment]
> https://pintorajs.vercel.app/demo/live-editor 可以作为一个 PWA 应用离线使用的，Edge 和 Chrome 应该都有作为 app 添加的方式。 你提到的作为独立 Markdown 的编辑器的话，应该超出 pintora 本身的能力了，比较好的方式可能是与各个流行的编辑器谈合作作为插件接入。


调用renderTo 方法来解析 pintora 代码。
```javasccript
import pintora from 'https://cdn.skypack.dev/@pintora/standalone';

const code = `sequenceDiagram
  title: Sequence Diagram Example
  autonumber
  User->>Pintora: render this
  activate Pintora
  loop Check input
    Pintora-->>Pintora: Has input changed?
  end
  Pintora-->>User: your figure here
  deactivate Pintora
  @note over User,Pintora: note over
  @note right of User: note aside actor
  @start_note right of User
  multiline note
  is possible
  @end_note
  == Divider ==`

const container = document.querySelector('.container')

  pintora.renderTo(code, {
    container,
    renderer: 'svg',
  })
```

那么我想自己实现以下试试。
你这有没有 更多的 详细的 关于 代码调用 的文档？

**Comment by hikerpig** [comment]
调用 API 的文档基本就在这里了，不太多 https://pintorajs.vercel.app/docs/advanced/api-usage/#pintora-api-in-the-browser

**Comment by TaiYouWeb** [comment]
> 调用 API 的文档基本就在这里了，不太多，碰到其他问题的话都可以在 issue 里讨论。 https://pintorajs.vercel.app/docs/advanced/api-usage/#pintora-api-in-the-browser

好的好的~
