### ISSUE TITLE
Created an Obsidian plugin to support Pintora: obsidian-pintora

### ISSUE THREAD

**Issue by amiaslee** [hikerpig/pintora#310]
I've created a plugin called **obsidian-pintora** that adds support for Pintora in the Obsidian Markdown editor. 
You can check out the project here: [obsidian-pintora](https://github.com/amiaslee/obsidian-pintora). 
For more details, feel free to refer to the [README.md](https://github.com/amiaslee/obsidian-pintora/blob/master/README.md).

**Comment by hikerpig** [comment]
Wow that's awesome !
I use Obsidian, too.
I'll add this cool project to README.
